const ErrorCodes = {
  MALFORMED_JSON_ERROR_CODE: 88,
  INVALID_CSV_ERROR_CODE: 89,
  EXTERNAL_SERVICE_ERROR_CODE: 91,
  INVALID_REQUEST_ERROR_CODE: 92,
  RUNTIME_ERROR_CODE: 99,
}

export default ErrorCodes;
